### ISSUE TITLE
TokenIdentifier differs from `Text` from ext-standard

### ISSUE THREAD

**Issue by dpori** [aviate-labs/ext.std#1]
https://github.com/aviate-labs/ext.std/blob/00cca45c06e669bb2d28e2bb356139cc26058971/src/Core.mo#L42

https://github.com/Toniq-Labs/extendable-token

Does the standard changed?

**Comment by q-uint** [comment]
Thank you for the issue!

This goal of this repository is not to provide a stable standard. It is just me experimenting in the open.
I have clarified this in ac6d91b, I am sorry for the misunderstanding.

> Did the standard change?

No, it did not.

I would recommend looking at the example implementations of the `EXT Standard`.
This [fork](https://github.com/jorgenbuilder/extendable-token) has a version that is compatible with `vessel`.

**Comment by q-uint** [comment]
Hi @dpori! I also added the EXT Std to the repo. It should follow the spec now.
